site_name: Monty Python
site_url: https://monty.arielle.codes/
repo_url: https://github.com/onerandomusername/monty-python/
edit_uri: edit/main/docs/
copyright: >
  Copyright &copy; 2025+ onerandomusername ·
  <a href="/terms">Terms of Service</a> ·
  <a href="/privacy">Privacy Policy</a>
theme:
  name: material
  logo: assets/images/logo.png
  palette:
    primary: blue grey
    accent: yellow
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.indexes
  - navigation.sections
  - navigation.tracking
  - toc.follow
  - navigation.top
  - search
  - search.suggest
  - search.highlight
  - social
  - content.action.edit
  - content.action.view
  - content.code.copy
  - content.code.annotate


plugins:
- privacy
- git-revision-date-localized

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- markdown_gfm_admonition
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.betterem

extra_css:
- assets/css/extra_admonitions.css

nav:
- Home: README.md
- Future Plans: future-plans.md
- Contributing:
  - contributing/README.md
  - Getting Started: contributing/getting-started.md
  - Design: contributing/design.md
  - Developer Commands: contributing/developer-commands.md
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/onerandomusername/monty-python
  - icon: fontawesome/brands/discord
    link: https://discord.gg/mPscM4FjWB
