"""feature rollouts

Revision ID: 2022_06_28_1
Revises: 19e4f2aee642
Create Date: 2022-06-28 10:46:16.693218

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2022_06_28_1"
down_revision = "19e4f2aee642"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rollouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("rollout_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rollout_to_percent", sa.SmallInteger(), nullable=False),
        sa.Column("rollout_hash_low", sa.SmallInteger(), nullable=False),
        sa.Column("rollout_hash_high", sa.SmallInteger(), nullable=False),
        sa.Column("update_every", sa.SmallInteger(), nullable=False),
        sa.Column(
            "hashes_last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("features", sa.Column("rollout", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_features_rollouts_id_rollout", "features", "rollouts", ["rollout"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_features_rollouts_id_rollout", "features", type_="foreignkey")
    op.drop_column("features", "rollout")
    op.drop_table("rollouts")
    # ### end Alembic commands ###
