"""add github comment linking

Revision ID: 2023_06_08_1
Revises: 2023_03_17_1
Create Date: 2023-06-08 16:08:05.842221

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2023_06_08_1"
down_revision = "2023_03_17_1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guild_config", sa.Column("github_comment_linking", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE guild_config SET github_comment_linking = true")

    op.alter_column("guild_config", "github_comment_linking", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guild_config", "github_comment_linking")
    # ### end Alembic commands ###
