"""allow disabling codesnippets

Revision ID: 2023_03_17_1
Revises: 2022_06_28_1
Create Date: 2023-03-17 21:01:37.638503

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2023_03_17_1"
down_revision = "2022_06_28_1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guild_config", sa.Column("git_file_expansions", sa.Boolean(), nullable=True))
    op.add_column("guild_config", sa.Column("github_issue_linking", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE guild_config SET git_file_expansions = true")
    op.execute("UPDATE guild_config SET github_issue_linking = true")

    op.alter_column("guild_config", "git_file_expansions", nullable=False)
    op.alter_column("guild_config", "github_issue_linking", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guild_config", "git_file_expansions")
    op.drop_column("guild_config", "github_issue_linking")
    # ### end Alembic commands ###
