"""add per-guild configuration

Revision ID: 50ddfc74e23c
Revises: d1f327f1548f
Create Date: 2022-05-22 01:56:44.036037

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "50ddfc74e23c"
down_revision = "d1f327f1548f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_config",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("prefix", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guild_config")
    # ### end Alembic commands ###
