"""Set up the documentation tables

Revision ID: 6a57a6d8d400
Revises:
Create Date: 2022-05-20 03:06:27.335042

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "6a57a6d8d400"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "docs_inventory",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("inventory_url", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("guilds_whitelist", postgresql.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("guilds_blacklist", postgresql.ARRAY(sa.BigInteger()), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("docs_inventory")
    # ### end Alembic commands ###
